### ISSUE TITLE
jupyterlab extension package installs fail with 0.9.1

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/jupyter-packaging#81]
This command:

```
jupyter labextension install @jupyterlab/server-proxy
```
exits with the following error:

```
---> Running in d4a404eceeb0
/srv/conda/envs/notebook/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/jupyter-labextension", line 5, in <module>
    from jupyterlab.labextensions import main
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyterlab/labapp.py", line 15, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyterlab_server/app.py", line 7, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_server/__init__.py", line 15, in <module>
    from ._version import version_info, __version__
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_server/_version.py", line 9, in <module>
    version_info = get_version_info(__version__)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 248, in get_version_info
    version_info = [parsed.major, parsed.minor, parsed.micro]
AttributeError: 'Version' object has no attribute 'major'
```

I think this was introduced in https://github.com/jupyter/jupyter-packaging/commit/bb68c8809b2cf756491c61f444764eef5cba5cef#diff-505fa72595b8bee2cea07dead97c94c69a07bb84219e5d66ddb579cffe0bee6c.

I can reproduce this behavior of `pkg_resources` with just plain python:

```python
>>> from pkg_resources import parse_version
>>> ver = parse_version('0.1.1')
>>> ver.major
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Version' object has no attribute 'major'
>>> ver = parse_version('v0.1.1')
>>> ver.major
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Version' object has no attribute 'major'
>>> 
```

**Comment by yuvipanda** [comment]
So this works on setuptools version 56.0 (latest), but not 49.2 (what I had before). I think either jupyter_packaging should be backwards compatible, or express a version requirement

**Comment by echarles** [comment]
> backwards compatible, or express a version requirement

I remember having such troubles month ago, but don't hit that anymore. Version requirement would be best IMHO
